# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "ahci" "usbhid" "usb_storage" "uas" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/887f354a-c4fc-444f-8a18-5d835649554e";
      fsType = "btrfs";
      options = [ "subvol=@" ];
    };

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/887f354a-c4fc-444f-8a18-5d835649554e";
      fsType = "btrfs";
      options = [ "subvol=@home" ];
    };

  fileSystems."/root" =
    { device = "/dev/disk/by-uuid/887f354a-c4fc-444f-8a18-5d835649554e";
      fsType = "btrfs";
      options = [ "subvol=@root" ];
    };

  fileSystems."/persist" =
    { device = "/dev/disk/by-uuid/887f354a-c4fc-444f-8a18-5d835649554e";
      fsType = "btrfs";
      options = [ "subvol=@persist" ];
    };

  fileSystems."/nix" =
    { device = "/dev/disk/by-uuid/887f354a-c4fc-444f-8a18-5d835649554e";
      fsType = "btrfs";
      options = [ "subvol=@nix" ];
    };

  fileSystems."/.snapshots" =
    { device = "/dev/disk/by-uuid/887f354a-c4fc-444f-8a18-5d835649554e";
      fsType = "btrfs";
      options = [ "subvol=@snapshots" ];
    };

  fileSystems."/var/log" =
    { device = "/dev/disk/by-uuid/887f354a-c4fc-444f-8a18-5d835649554e";
      fsType = "btrfs";
      options = [ "subvol=@log" ];
    };

  fileSystems."/var/lib/docker" =
    { device = "/dev/disk/by-uuid/887f354a-c4fc-444f-8a18-5d835649554e";
      fsType = "btrfs";
      options = [ "subvol=@docker" ];
    };

  fileSystems."/var/lib/libvirt/images" =
    { device = "/dev/disk/by-uuid/887f354a-c4fc-444f-8a18-5d835649554e";
      fsType = "btrfs";
      options = [ "subvol=@images" ];
    };

  fileSystems."/var/lib/machines" =
    { device = "/dev/disk/by-uuid/887f354a-c4fc-444f-8a18-5d835649554e";
      fsType = "btrfs";
      options = [ "subvol=@machines" ];
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/0791-8482";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices = [ ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp7s0.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp6s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
