# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "thunderbolt" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/38cf92fe-67dd-4cad-9ff1-39de97242e01";
      fsType = "btrfs";
      options = [ "subvol=@" ];
    };

  boot.initrd.luks.devices."crypt".device = "/dev/disk/by-uuid/23312963-d0b8-4f50-a4fe-709bfdcba0f1";

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/38cf92fe-67dd-4cad-9ff1-39de97242e01";
      fsType = "btrfs";
      options = [ "subvol=@home" ];
    };

  fileSystems."/root" =
    { device = "/dev/disk/by-uuid/38cf92fe-67dd-4cad-9ff1-39de97242e01";
      fsType = "btrfs";
      options = [ "subvol=@root" ];
    };

  fileSystems."/persist" =
    { device = "/dev/disk/by-uuid/38cf92fe-67dd-4cad-9ff1-39de97242e01";
      fsType = "btrfs";
      options = [ "subvol=@persist" ];
    };

  fileSystems."/nix" =
    { device = "/dev/disk/by-uuid/38cf92fe-67dd-4cad-9ff1-39de97242e01";
      fsType = "btrfs";
      options = [ "subvol=@nix" ];
    };

  fileSystems."/.snapshots" =
    { device = "/dev/disk/by-uuid/38cf92fe-67dd-4cad-9ff1-39de97242e01";
      fsType = "btrfs";
      options = [ "subvol=@snapshots" ];
    };

  fileSystems."/var/log" =
    { device = "/dev/disk/by-uuid/38cf92fe-67dd-4cad-9ff1-39de97242e01";
      fsType = "btrfs";
      options = [ "subvol=@log" ];
    };

  fileSystems."/var/lib/docker" =
    { device = "/dev/disk/by-uuid/38cf92fe-67dd-4cad-9ff1-39de97242e01";
      fsType = "btrfs";
      options = [ "subvol=@docker" ];
    };

  fileSystems."/var/lib/libvirt/images" =
    { device = "/dev/disk/by-uuid/38cf92fe-67dd-4cad-9ff1-39de97242e01";
      fsType = "btrfs";
      options = [ "subvol=@images" ];
    };

  fileSystems."/var/lib/machines" =
    { device = "/dev/disk/by-uuid/38cf92fe-67dd-4cad-9ff1-39de97242e01";
      fsType = "btrfs";
      options = [ "subvol=@machines" ];
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/661D-9578";
      fsType = "vfat";
      options = [ "fmask=0022" "dmask=0022" ];
    };

  swapDevices = [ ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp1s0f0.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp2s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
